version: "3"
services:
    # バックエンド
    flask:
        container_name: flask
        build: ./flask
        volumes:
            - ./flask:/flask
        ports:
            - "3000:3000"
        # command: flask run --host 0.0.0.0 --port 5000
        environment:
            - FLASK_DEBUG=1
            - FLASK_ENV=development
            - FLASK_APP=flaskr
        tty: true
        # privileged: true